##**Compute Levenshtein Distance between Text and Key Words for Spam Classification** 

In [1]:
!pip install nltk
!pip install python-Levenshtein
!pip install PyPDF2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 50 kB 3.7 MB/s 
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp37-cp37m-linux_x86_64.whl size=149855 sha256=8c42c3173cd468eb334c66dc0f831e290c93a6de9b0c188db1f4a1faf3f65704
  Stored in directory: /root/.cache/pip/wheels/05/5f/ca/7c4367734892581bb5ff896f15027a932c551080b2abd3e00d
Successfully built python-Levenshtein
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 201 kB 8.4 MB/s 


In [2]:
from Levenshtein import distance as lev
import nltk
import PyPDF2
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


## Define Keywords and Corpus

In [3]:
# Define the Keywords for Levenshtein Distance
keywords = {
"AST_Task2":["covid",
"vaccine", 
"production", 
"mrna",
"manufacturing",
"chain",
"management", 
"operations", 
"rd", 
"research", 
"development",
"pfizer",
"moderna",
"biontech",
"lonza",
"sanofi", 
"curevac", 
"csl",
"luniabio", 
"knowledge", 
"gap"], 
"AST_Task3":
["covid",
"vaccine", 
"production", 
"mrna",
"manufacturing",
"chain",
"management", 
"operations", 
"rd", 
"research", 
"development",
"pfizer",
"moderna",
"biontech",
"lonza",
"sanofi", 
"curevac", 
"csl",
"luniabio", 
"knowledge", 
"gap"], 
"AST_Task4":
["alpha",
"sights",
"mr",
"ms",
"dr",
"prof",
"sir",
"madam",
"alphasights",
"dear",
"concern",
"yours",
"truly",
"faithfully",
"sincerely",
"regards",
"project",
"covid",
"manufacture",
"mrna",
"vaccine",
"consultation", 
"call",
"chain",
"management", 
"operations",
"rd", 
"research"
]}

In [7]:
from google.colab import files

uploaded = files.upload()
print(uploaded)

Saving 1bd95d4a-005b-4db7-89f3-a854fcf5b3b0submission.pdf to 1bd95d4a-005b-4db7-89f3-a854fcf5b3b0submission.pdf
{'1bd95d4a-005b-4db7-89f3-a854fcf5b3b0submission.pdf': b'%PDF-1.7\n\n4 0 obj\n(Identity)\nendobj\n5 0 obj\n(Adobe)\nendobj\n8 0 obj\n<<\n/Filter /FlateDecode\n/Length 195864\n/Length1 565036\n/Type /Stream\n>>\nstream\nx\x9c\xec\xbd\x07|\x1c\xc5\xdd7>[\xaew\x9d\xae\xf7.\xe9\xa4\xbb\xd3\x9d\xbad\xe9\xd4O]\xb6,#\xd9\x96-\xd9\x96q\xc1\xb8\n\x17\x0c\x98f\xc0\xf4\x1e\xbaC !1E\x92e#0-\xe0@\x12p\xc2\x13\x08$$$\x90\x90\x87\x90\xa0\x84\x10J0\xd6\xe9\xff\x9b\x9d;\xe9$\xcb\xc6\x90\xbc\xff\xe7y?\xafF\x9e\xfb\xee\xce\xce\xcc\xce\xfc\xda\xfcfvv\x8d(\x84\x90\x16~X\xd4[\xd3\xd1P\xbf\xe0\xed\xa1\xc5Hx\xf1\x0e\x84,#\xb5U5\x0b\xdf\x11\x1c\xe8G\xd4\x05\x0f#$y\xa3\xb6\xaa\xb9\xba\xf6\xc1\x82\xeb\x10\xb5\xe3\xb7P\xe0\xd5\xfa\x9a\xda\xba\xa3?}\xf3\x1d\xc4>\xf5\x10B\xfc?\xd4\xb7\xb7u4|\xfa\xe6?\x10\xfb\xc25\x88y\xfa/\xf5\x1d\x9dU\xdf\x97~t5\xa2\xf6\t\x11\x13\xbe\xb7\xad#\x18\xbe\xef\xa3\xe2L\x84\xa8

In [8]:
pdf = open('1bd95d4a-005b-4db7-89f3-a854fcf5b3b0submission.pdf', 'rb')  
reader = PyPDF2.PdfFileReader(pdf) 
'''   
# printing number of pages in pdf file 
print(pdfReader.numPages) 
    
# creating a page object 
pageObj = pdfReader.getPage(0) 
'''    
# extracting text from page 
corpus = reader.getPage(0).extractText()
print(corpus)
    
# closing the pdf file object 
pdf.close() 

Identify the knowledge gap our client is facing ： 
The client has insufficient knowledge in mRNA manufacturing processes and key 
feasibility constraints across manufacturing chain. Their main question includes the 
key upstream and downstream process inputs to mRNA vaccine manufacturing, 
sustainability of key inputs in the vaccine manufacturing process, the key relative 
advantages of current mRNA vaccine manufacturers, the expected approx. cost range 
of the manufacturing process and the prospect of mRNA vaccine production to scale 
globally across 1.5 years: 
 
Research the key players of COVID vaccine: 
Pfizer is one of the global largest biopharmaceutical companies, working in the R&D 
and manufacture of medicines and vaccines. BioNTech is a biotechnology firm, 
focusing on the development of mRNA technology for vaccines and Immunotherapy. 
4 billion doses of the Pfizer-BioNTech COVID-19 Vaccine are expected to be produced 
worldwide in 2022. Pfizer as the distributor in Europe a

/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'1' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'2' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'3' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'38' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'37' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: Superfluous whitespace found in object header b'11' b'0'
  PdfReadWarning,
/usr/local/lib/python3.7/dist-packages/PyPDF2/_reader.py:1155: PdfReadWarning: 

### Preprocessing - Remove Punctuations and Stemming

In [15]:
import string
import numpy as np
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

# Lowercase
corpus = corpus.lower()

# Punctuations
corpus_alpha = "".join([char for char in corpus if char not in string.punctuation])

# Tokenization
words = word_tokenize(corpus_alpha)

# Stopword Filtering
stop_words = set(stopwords.words('english'))
filteredWords = [word for word in words if not word in stop_words]

# Stemming
# Optional - We can compare with and without Stemming
stemmer = PorterStemmer()
stemmedWords = [stemmer.stem(word) for word in filteredWords]

# Lemmatization
lemmatizedWords = filteredWords 
lemmatizer = WordNetLemmatizer()
lemmatizedWords = [lemmatizer.lemmatize(word) for word in lemmatizedWords]


In [16]:
# Visualize the words
print("FilteredWords")
print(filteredWords)
print("StemmedWords")
print(stemmedWords)
print("LemmatizedWords")
print(lemmatizedWords)

FilteredWords
['identify', 'knowledge', 'gap', 'client', 'facing', '：', 'client', 'insufficient', 'knowledge', 'mrna', 'manufacturing', 'processes', 'key', 'feasibility', 'constraints', 'across', 'manufacturing', 'chain', 'main', 'question', 'includes', 'key', 'upstream', 'downstream', 'process', 'inputs', 'mrna', 'vaccine', 'manufacturing', 'sustainability', 'key', 'inputs', 'vaccine', 'manufacturing', 'process', 'key', 'relative', 'advantages', 'current', 'mrna', 'vaccine', 'manufacturers', 'expected', 'approx', 'cost', 'range', 'manufacturing', 'process', 'prospect', 'mrna', 'vaccine', 'production', 'scale', 'globally', 'across', '15', 'years', 'research', 'key', 'players', 'covid', 'vaccine', 'pfizer', 'one', 'global', 'largest', 'biopharmaceutical', 'companies', 'working', 'rd', 'manufacture', 'medicines', 'vaccines', 'biontech', 'biotechnology', 'firm', 'focusing', 'development', 'mrna', 'technology', 'vaccines', 'immunotherapy', '4', 'billion', 'doses', 'pfizerbiontech', 'covid1

## Generate Levenshtein Matrix

In [21]:
print("FilteredWords")
temp = []
uniquecount = 0
count0=0
count1=0
count2=0
levMatrix = np.zeros((len(filteredWords),len(keywords['AST_Task2'])))
for text_word in range(len(filteredWords)):
  for key_word in range(len(keywords['AST_Task2'])):
    lev_dist = lev(filteredWords[text_word], keywords['AST_Task2'][key_word])
    levMatrix[text_word][key_word] = lev_dist
    if lev_dist == 0:
      if filteredWords[text_word] not in temp:
        uniquecount += 1
        temp.append(filteredWords[text_word])
      count0 += 1
    if lev_dist == 1:
      count1 += 1
    if lev_dist == 2:
      count2 += 1

print(np.matrix(levMatrix))
print("FilteredWords")
print("Edit Distance Count: 0: {}, 1: {}, 2: {}".format(count0, count1, count2))
print(uniquecount)
print(temp)
print(".......................................................................")

print("StemmedWords")
count0=0
count1=0
count2=0
levMatrix = np.zeros((len(stemmedWords),len(keywords['AST_Task2'])))
for text_word in range(len(stemmedWords)):
  for key_word in range(len(keywords['AST_Task2'])):
    lev_dist = lev(stemmedWords[text_word], keywords['AST_Task2'][key_word])
    levMatrix[text_word][key_word] = lev_dist
    if lev_dist == 0:
      count0 += 1
    if lev_dist == 1:
      count1 += 1
    if lev_dist == 2:
      count2 += 1
# print(np.matrix(levMatrix))
print("Edit Distance Count: 0: {}, 1: {}, 2: {}".format(count0, count1, count2))
print(".......................................................................")

print("LemmatizedWords")
temp = []
uniquecount = 0
count0=0
count1=0
count2=0
levMatrix = np.zeros((len(lemmatizedWords),len(keywords['AST_Task2'])))
for text_word in range(len(lemmatizedWords)):
  for key_word in range(len(keywords['AST_Task2'])):
    lev_dist = lev(lemmatizedWords[text_word], keywords['AST_Task2'][key_word])
    levMatrix[text_word][key_word] = lev_dist
    if lev_dist == 0:
      count0 += 1
      if filteredWords[text_word] not in temp:
        uniquecount += 1
        temp.append(filteredWords[text_word])
    if lev_dist == 1:
      count1 += 1
    if lev_dist == 2:
      count2 += 1
print("Edit Distance Count: 0: {}, 1: {}, 2: {}".format(count0, count1, count2))
print(uniquecount)
print(temp)
# print(np.matrix(levMatrix))
print(".......................................................................")


FilteredWords
[[ 7.  7.  7. ...  8.  9.  8.]
 [ 7.  8.  9. ...  9.  0.  9.]
 [ 5.  6. 10. ...  7.  9.  0.]
 ...
 [ 7.  6.  3. ...  8.  8.  9.]
 [ 7.  1.  9. ...  8.  9.  7.]
 [ 7.  7.  8. ...  8.  6.  7.]]
FilteredWords
Edit Distance Count: 0: 53, 1: 4, 2: 19
19
['knowledge', 'gap', 'mrna', 'manufacturing', 'chain', 'vaccine', 'production', 'research', 'covid', 'pfizer', 'rd', 'biontech', 'development', 'moderna', 'lonza', 'sanofi', 'curevac', 'csl', 'luniabio']
.......................................................................
StemmedWords
Edit Distance Count: 0: 28, 1: 16, 2: 23
.......................................................................
LemmatizedWords
Edit Distance Count: 0: 56, 1: 1, 2: 20
20
['knowledge', 'gap', 'mrna', 'manufacturing', 'chain', 'vaccine', 'production', 'research', 'covid', 'pfizer', 'rd', 'vaccines', 'biontech', 'development', 'moderna', 'lonza', 'sanofi', 'curevac', 'csl', 'luniabio']
............................................................

* Stemming makes it more difficult to count number of keywords
* Lemmatization makes it easier to count keywords

## Cosine Similarity Matrix between Corpus and Keywords